Raise psr/simple-cache to ^2.0|^3.0 and PHP to ^8.0
yiisoft/cache-file pull request #44
Opened 2022-07-09 14:00 UTC by dehbka

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | 43

2022-07-09 19:04 UTC, rustamwin reviewed
Version 7.4 needs to be removed from GitHub workflows. And of course need changelog line.

2022-07-10 04:20 UTC, rustamwin requested changes

2022-07-10 04:20 UTC, rustamwin commented on CHANGELOG.md
> +## 2.0.0 July 10, 2022
```suggestion
## 2.0.0 under development
```
The release date will be automatically generated when it is released.

2022-07-10 04:30 UTC, rustamwin reviewed
[These](https://github.com/yiisoft/cache-file/pull/44/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL4-L8) lines should be removed.

2022-07-10 04:30 UTC, rustamwin commented on CHANGELOG.md
> +- Chg: Raise the minimum `psr/simple-cache` version to `^2.0|^3.0` and the minimum PHP version to `^8.0`
```suggestion
- Chg #44: Raise the minimum `psr/simple-cache` version to `^2.0|^3.0` and the minimum PHP version to `^8.0` (@dehbka)
```

2022-07-10 08:49 UTC, rustamwin approved these changes

2022-07-12 11:05 UTC, vjik requested changes

2022-07-12 11:05 UTC, vjik commented on src/FileCache.php
>       * @param mixed $key
This is string. phpdoc can be removed

2022-07-14 19:43 UTC, vjik requested changes

2022-07-14 19:43 UTC, vjik commented on src/FileCache.php
> -            }
From PHP 8 we should check on empty string instead false. Seems, need test for this case (in this PR or create issue).

2022-07-20 10:59 UTC, vjik approved these changes

2022-07-21 09:46 UTC, merged

2022-07-21 09:46 UTC, samdark commented
Thanks!