fix chmod for directories
yiisoft/cache-file pull request #47
Opened 2022-09-09 16:17 UTC by dehbka

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | [46](https://github.com/yiisoft/cache-file/issues/46)

2022-09-09 16:50 UTC, terabytesoftw approved these changes

2022-09-15 20:48 UTC, samdark requested changes

2022-09-15 20:48 UTC, samdark commented on src/FileCache.php
> +        chmod($new->cachePath, $directoryMode);
It should be removed since `withDirectoryMode()` is meant to configure `FileCache`, not to execute anything immediately.

2022-09-15 20:48 UTC, samdark commented on src/FileCache.php
> +        if (true === is_dir($path)) {
```suggestion
        if (is_dir($path)) {
```

2022-09-15 20:48 UTC, samdark commented on src/FileCache.php
> +        if (true === $result) {
```suggestion
        if ($result) {
```

2022-09-15 20:48 UTC, samdark commented on src/FileCache.php
> +        $result = !is_file($path) && mkdir(directory: $path, recursive: true) && is_dir($path);
Any reason not to use [mkdir's permissions parameter](https://www.php.net/manual/en/function.mkdir.php)?

2022-09-16 19:12 UTC, vjik requested changes
Need line in changelog

2022-09-17 09:31 UTC, vjik approved these changes

2022-09-17 09:31 UTC, vjik commented on CHANGELOG.md
> +- Chg #47: fix permissions for directories (@dehbka)
```suggestion
- Chg #47: Set permissions for new directory via `chmod()` (@dehbka)
```

2022-09-18 13:51 UTC, merged