Clear stat cache in FileCache::set()
yiisoft/cache-file pull request #85
Opened 2024-12-30 17:15 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/yii2/pull/20304

2024-12-30 18:57 UTC, terabytesoftw approved these changes

2024-12-30 19:46 UTC, xepozz approved these changes

2024-12-30 19:54 UTC, vjik requested changes

2024-12-30 19:54 UTC, vjik commented on CHANGELOG.md
> +- Bug #85: Clear stat cache in `FileCache::set()` (samdark)
```suggestion
- Bug #85: Clear stat cache in `FileCache::set()` (@samdark)
```

2024-12-30 19:54 UTC, vjik commented on src/FileCache.php
> +            clearstatcache();
Need a test

2024-12-30 19:54 UTC, vjik commented on src/FileCache.php
> +            clearstatcache();
Pass file name to `clearstatcache()` to affect only one file.

2024-12-30 20:39 UTC, samdark commented
@vjik good ideas. Thanks. Applied.

2024-12-30 21:00 UTC, vjik commented on src/FileCache.php
> +            clearstatcache(false, $file);
```suggestion
            clearstatcache(true, $file);
```

It works only when clear_realpath_cache is true.

2025-01-01 19:39 UTC, samdark commented on src/FileCache.php
> +            clearstatcache(false, $file);
And we don't care about realpath cache, so passing any parameters does not make sense.

2025-01-05 15:08 UTC, vjik commented on src/FileCache.php
> +            clearstatcache(false, $file);
I'm tested this case. `clearstatcache(false, $file);` is cleared cache of modified time.

2025-01-05 15:11 UTC, vjik approved these changes

2025-01-06 14:38 UTC, merged